title: "Shay's Digital Home"
description: "A personal journal, digital garden, and collection of thoughts."
url: "https://shayshoon.github.io"
author: "Shay"
subscribe_action_url: "https://script.google.com/macros/s/AKfycbyUxP9qkDCe0vn3aI8AYhL8za985_1z-G-sG7ThEuuKQp9VgsW3p1Epdewv_u-NHHmdLw/exec"

collections:
  posts:
    permalink: /journal/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
