title: "Shay's Digital Home"
description: "A personal journal, digital garden, and collection of thoughts."
url: "https://shayshoon.github.io"
author: "Shay"

collections:
  posts:
    permalink: /journal/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
