title: "Shay's Digital Home"
description: "A personal journal, digital garden, and collection of thoughts."
url: "https://shayshoon.github.io"
author: "Shay"
subscribe_action_url: "https://script.google.com/macros/s/AKfycbyI2t_KUB7w0onmvN3ETfVcyF_iknvgMlPycRZakf8I-Nmyha03QF1RIzuuFJ1-gZhAUw/exec"

collections:
  posts:
    permalink: /journal/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      dir: "rtl"
